import * as cheerio from 'cheerio';
import type { Registry } from './types';

/**
 * Pass 2 of the fixture import: rewrite one captured page into a committable
 * fixture.
 *
 * Two things are being removed, for two different reasons:
 *
 *  - **Private data** (names, IDs, tokens, session values). Non-negotiable:
 *    these fixtures live in a public repository.
 *  - **PowerSchool's own JavaScript, CSS and icon sprites.** Those are not ours
 *    to redistribute, and they are also 90% of the file size. The fixture
 *    server supplies an original Schoology-like stylesheet instead, and can
 *    serve the real captured assets from the gitignored `.local-schoology/`
 *    directory for developers who have the capture.
 *
 * What is deliberately *preserved*, because the extension depends on it:
 * element hierarchy, semantic IDs and classes, `data-id`/`data-parent-id`
 * relationships, `data-start` semantics, ARIA structure, and route shapes.
 */

/** Nodes removed wholesale, with the reason each one goes. */
const REMOVED_SELECTORS = [
  'script', // inline Drupal.settings holds CSRF/session values; bundles are proprietary
  'style', // PowerSchool CSS
  'link[rel="stylesheet"]',
  'link[rel="preload"]',
  'link[rel="dns-prefetch"]',
  'link[rel="preconnect"]',
  'noscript',
  'iframe', // LTI / external tools: third-party boundaries
  '#neon-sprite-sheet-container', // ~750KB of PowerSchool icon sprites
  '#pds-icon-sprite',
  '#__SVG_SPRITE_NODE__',
  // Every inline SVG: these are PowerSchool/Neon/PDS icon artwork, so they are
  // both not ours to redistribute and the bulk of the remaining file size.
  // Icons are simply absent from fixtures; layout is supplied by our own
  // Schoology-like stylesheet instead.
  'svg',
  '[id^="bettercanvas"]', // another extension's nodes, present in the capture
  '[class*="bettercanvas"]',
];

/** Attributes that can carry tokens or per-session values. */
const REMOVED_ATTRIBUTES = [
  'nonce',
  'integrity',
  'crossorigin',
  'data-gainsight',
  'original-title',
];

/** Long opaque strings that look like credentials rather than identifiers. */
const SECRET_PATTERNS: RegExp[] = [
  /eyJ[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]+/g, // JWT
  /\b[A-Fa-f0-9]{32,}\b/g, // hex digests, attachment source tokens
  /\b[A-Za-z0-9_-]{40,}\b/g, // base64url-ish secrets
];

export interface SanitizeOptions {
  registry: Registry;
  /** Page title to use, replacing the captured one. */
  title: string;
  /** Path the fixture server will serve this page at, recorded as a comment. */
  route: string;
}

export function sanitizePage(html: string, options: SanitizeOptions): string {
  const { registry } = options;
  const $ = cheerio.load(html);

  for (const selector of REMOVED_SELECTORS) $(selector).remove();

  // Comments can hold build metadata and, in saved pages, the original URL.
  $('*')
    .contents()
    .filter((_, node) => node.type === 'comment')
    .remove();

  $('*').each((_, node) => {
    if (node.type !== 'tag') return;
    const el = $(node);
    for (const attribute of REMOVED_ATTRIBUTES) el.removeAttr(attribute);

    // Browser-save artifacts pointing back at the captured session.
    const saved = el.attr('data-saved-url') ?? el.attr('saved_url');
    if (saved !== undefined) {
      el.removeAttr('data-saved-url');
      el.removeAttr('saved_url');
    }
  });

  rewriteAssetReferences($);
  replaceUserGeneratedContent($);
  rewriteTextAndAttributes($, registry);

  // `<head>` is rebuilt rather than filtered: the captured one is almost
  // entirely inline PowerSchool CSS.
  const head = $('head');
  head.empty();
  head.append('<meta charset="utf-8">');
  head.append('<meta name="viewport" content="width=device-width, initial-scale=1">');
  head.append(`<title>${escapeHtml(options.title)} | Schoology</title>`);
  head.append('<link rel="stylesheet" href="/__bs_fixture/schoology-shell.css">');
  // Optional: real captured CSS, served only when .local-schoology/ has it.
  head.append('<link rel="stylesheet" href="/__schoology_assets/captured.css">');
  head.append('<script src="/__bs_fixture/bootstrap.js" defer></script>');

  const body = $('body');
  body.prepend(
    `<!-- Better Schoology sanitized fixture. Route: ${options.route}. ` +
      'Generated by scripts/import-schoology-fixtures.ts from a local capture. ' +
      'All names, IDs and tokens are synthetic. -->',
  );

  return `<!doctype html>\n${$.html()}\n`;
}

/**
 * Containers holding text a person wrote: announcements, posts, comments and
 * assignment descriptions. Their *structure* is what the extension parses, so
 * the elements stay; only the prose is replaced.
 */
const USER_CONTENT_SELECTORS = [
  '.update-body',
  '.post-body',
  '.comment-body',
  '.item-body',
  '.s-rte',
  '.assignment-body',
  '.info-text p',
  // Feed posts carry linked documents and web-link previews whose titles are
  // written by staff and can name real people, events and schools.
  '.edge-main',
  '.s-edge-summary',
  // Uploaded filenames are equally author-written.
  '.attachments-file-name',
  '.attachments-link',
];

const SYNTHETIC_SENTENCES = [
  'Example announcement text for the local fixture environment.',
  'This placeholder replaces content a real person wrote.',
  'Structure is preserved; the words are synthetic.',
  'Sample course update used only for Better Schoology development.',
];

/** Attributes inside user content that repeat the author's own words. */
const USER_CONTENT_ATTRIBUTES = ['title', 'alt', 'aria-label', 'data-title'];

/**
 * Overwrites everything a person wrote inside user-content containers.
 *
 * Real posts, comments and shared-document titles can name students, staff,
 * schools and events in ways no pattern-based scrubber can reliably catch, so
 * none of that prose is kept -- in text nodes *or* in the `title`/`alt`
 * attributes that mirror it. Replacing content rather than the containers
 * keeps nesting, attachments and feed markup exactly as Schoology rendered them.
 */
function replaceUserGeneratedContent($: cheerio.CheerioAPI): void {
  let counter = 0;
  const nextSentence = (): string => SYNTHETIC_SENTENCES[counter++ % SYNTHETIC_SENTENCES.length]!;

  for (const selector of USER_CONTENT_SELECTORS) {
    $(selector).each((_, container) => {
      const scope = $(container).find('*').addBack();

      scope.contents().each((__, node) => {
        if (node.type !== 'text') return;
        if (!(node.data ?? '').trim()) return;
        node.data = nextSentence();
      });

      scope.each((__, node) => {
        if (node.type !== 'tag') return;
        const el = $(node);
        for (const attribute of USER_CONTENT_ATTRIBUTES) {
          if (el.attr(attribute)) el.attr(attribute, nextSentence());
        }
      });
    });
  }
}

/**
 * Points saved-page asset references at the fixture server.
 *
 * Browser "Save Page As" writes `<page>_files/name_XXXX.ext` and appends a
 * per-page dedupe suffix; both are normalized away so every page references the
 * same shared asset path.
 */
function rewriteAssetReferences($: cheerio.CheerioAPI): void {
  const normalize = (value: string): string | null => {
    const decoded = safeDecode(value);

    const savedFile = decoded.match(/(?:^|\/)([^/]+_files)\/(.+)$/);
    if (savedFile) return `/__schoology_assets/${normalizeAssetName(savedFile[2]!)}`;

    if (/^https?:\/\/(asset-cdn|ui)\.schoology\.com\//i.test(decoded)) {
      const name = decoded.split('/').pop() ?? '';
      return `/__schoology_assets/${normalizeAssetName(name)}`;
    }

    if (/^https?:\/\/assets\.powerschool\.com\//i.test(decoded)) {
      const name = decoded.split('/').pop() ?? '';
      return `/__schoology_assets/${normalizeAssetName(name)}`;
    }

    return null;
  };

  $('img[src], source[src], video[poster], input[type="image"][src]').each((_, node) => {
    const el = $(node);
    for (const attribute of ['src', 'poster'] as const) {
      const value = el.attr(attribute);
      if (!value) continue;
      const next = normalize(value);
      if (next) el.attr(attribute, next);
    }
    // Saved pages keep multi-resolution sets pointing at the capture directory.
    el.removeAttr('srcset');
  });
}

function normalizeAssetName(name: string): string {
  const decoded = safeDecode(name);
  const withoutQuery = decoded.split(/[?#]/)[0] ?? decoded;
  // Strip the browser-save dedupe suffix (`icon_9sNy.png` -> `icon.png`).
  const cleaned = withoutQuery.replace(/_[A-Za-z0-9]{4}(\.[A-Za-z0-9]+)$/, '$1');
  // The tenant logo filename embeds the real school name.
  if (/logo/i.test(cleaned) && !/^logo/i.test(cleaned)) return 'school-logo.png';
  return cleaned.toLowerCase();
}

function safeDecode(value: string): string {
  try {
    return decodeURIComponent(value);
  } catch {
    return value;
  }
}

/**
 * Attributes handled as free text (identifying strings can appear in them).
 * Every *other* attribute still gets identifier remapping and secret redaction
 * -- the captures use custom attributes such as `course="..."` and
 * `caption_href="..."` that would otherwise carry data straight through.
 */
const TEXT_ATTRIBUTES = new Set([
  'title',
  'alt',
  'aria-label',
  'placeholder',
  'value',
  'content',
  'defaulttext',
]);

/** Attributes whose values are CSS or class lists, not data. */
const STRUCTURAL_ATTRIBUTES = new Set(['class', 'style']);

function looksLikeUrl(value: string): boolean {
  return value.includes('/') || /^https?:/i.test(value) || value.startsWith('#');
}

function rewriteTextAndAttributes($: cheerio.CheerioAPI, registry: Registry): void {
  $('*')
    .contents()
    .each((_, node) => {
      if (node.type !== 'text') return;
      const original = node.data ?? '';
      const next = replaceAll(original, registry);
      if (next !== original) node.data = next;
    });

  $('*').each((_, node) => {
    if (node.type !== 'tag') return;
    const el = $(node);

    for (const [attribute, rawValue] of Object.entries(node.attribs ?? {})) {
      if (!rawValue) continue;

      if (STRUCTURAL_ATTRIBUTES.has(attribute)) {
        // Class lists can embed IDs (`comment-textarea-<assignmentId>`), and
        // inline styles can embed asset URLs. Neither holds free text.
        let next = replaceIdsIn(rawValue, registry);
        if (attribute === 'style') next = next.replace(/url\((['"]?)data:[^)]*\1\)/gi, 'none');
        el.attr(attribute, next);
        continue;
      }

      let next = looksLikeUrl(rawValue) ? rewriteUrl(rawValue, registry) : rawValue;
      next = TEXT_ATTRIBUTES.has(attribute) ? replaceAll(next, registry) : redactAttribute(next, registry);

      if (LABEL_ATTRIBUTES.has(attribute)) next = safeLabel(next, directText(node), registry);

      el.attr(attribute, next);
    }
  });
}

/**
 * Attributes that display free text to the user and are therefore the last
 * place author-written content can hide.
 */
const LABEL_ATTRIBUTES = new Set(['title', 'alt', 'aria-label']);

/**
 * Reduces a label attribute to something known-safe.
 *
 * Even after prose containers are scrubbed, a `title` or `alt` anywhere else in
 * the page can carry text a person wrote -- an attachment's real filename, a
 * shared document's title. Rather than trying to classify such values, the rule
 * is inverted: a label survives only if it is one of the sanitizer's own
 * synthetic replacements (a mapped course, person or school name, which the
 * extension legitimately reads from `.course-title[title]`). Anything else is
 * replaced by the element's own already-sanitized text, keeping the attribute
 * present and the DOM shape intact.
 */
function safeLabel(value: string, ownText: string, registry: Registry): string {
  const trimmed = value.trim();
  if (!trimmed) return value;

  if (syntheticValues(registry).has(trimmed)) return value;

  const fallback = ownText.replace(/\s+/g, ' ').trim();
  return fallback ? fallback.slice(0, 80) : GENERIC_LABEL;
}

const GENERIC_LABEL = 'Example label';

/**
 * Text from an element's own text nodes only.
 *
 * Descendant text is deliberately excluded: `.text()` on a container such as a
 * filter menu concatenates every option into one long unspaced run, which is
 * both a useless label and indistinguishable from an opaque token.
 */
function directText(node: unknown): string {
  let text = '';
  const children = (node as { children?: Array<{ type: string; data?: string }> }).children ?? [];
  for (const child of children) {
    if (child.type === 'text') text += child.data ?? '';
  }
  return text;
}

let syntheticCache: { registry: Registry; values: Set<string> } | null = null;

/** The set of replacement strings the sanitizer itself introduced. */
function syntheticValues(registry: Registry): Set<string> {
  if (syntheticCache?.registry === registry) return syntheticCache.values;

  const values = new Set<string>();
  for (const replacement of registry.strings.values()) {
    values.add(replacement);
    // Course labels also appear as `Name: Section`.
    for (const other of registry.strings.values()) {
      if (other !== replacement) values.add(`${replacement}: ${other}`);
    }
  }

  syntheticCache = { registry, values };
  return values;
}

/** Identifier remapping plus secret redaction, for attributes that are not free text. */
function redactAttribute(value: string, registry: Registry): string {
  let next = replaceIdsIn(value, registry);
  for (const pattern of SECRET_PATTERNS) {
    pattern.lastIndex = 0;
    next = next.replace(pattern, (match) => (/^[0-9]+$/.test(match) ? match : 'REDACTED'));
  }
  return next;
}

/**
 * Rewrites a URL: the captured tenant host becomes a root-relative path (so the
 * fixture server sees the same routes real Schoology would), and every embedded
 * identifier is remapped.
 */
function rewriteUrl(value: string, registry: Registry): string {
  let next = value;

  for (const host of registry.hosts) {
    next = next.replace(new RegExp(`https?://${escapeRegex(host)}`, 'gi'), '');
  }

  if (/^https?:\/\//i.test(next)) {
    /*
     * Anything still absolute points off-tenant. Third-party links in feed
     * posts are staff-shared documents whose URLs embed document IDs, so the
     * target is dropped entirely and only the shape is kept.
     */
    next = /schoology\.com|powerschool\.com/i.test(next) ? '#external' : 'https://example.com/';
  }

  next = replaceIdsIn(next, registry);
  next = replaceAll(next, registry);
  next = stripUnknownQueryParameters(next);

  // Attachment source paths end in a per-session token, not a filename.
  next = next.replace(
    /\/attachment\/(\d+)\/source\/[A-Za-z0-9._-]+/g,
    '/attachment/$1/source/example.pdf',
  );

  // Anything else long and opaque left in a URL is treated as a credential.
  for (const pattern of SECRET_PATTERNS) {
    pattern.lastIndex = 0;
    next = next.replace(pattern, (match) => (/^[0-9]+$/.test(match) ? match : 'REDACTED'));
  }

  return next || '#';
}

/**
 * Query parameters the extension's router actually reads. Everything else is
 * dropped: Schoology's `/link?path=<encoded url>` redirects embed whole
 * third-party document URLs, which no amount of ID remapping would clean.
 */
const ALLOWED_QUERY_PARAMS = new Set(['f', 'list_filter', 'page', 'filter', 'past', 'fixture']);

function stripUnknownQueryParameters(value: string): string {
  const separator = value.indexOf('?');
  if (separator === -1) return value;

  const [path, rest] = [value.slice(0, separator), value.slice(separator + 1)];
  const [query, hash] = rest.split('#');

  const kept = (query ?? '')
    .split('&')
    .filter((pair) => ALLOWED_QUERY_PARAMS.has(decodeURIComponent(pair.split('=')[0] ?? '')));

  const suffix = kept.length > 0 ? `?${kept.join('&')}` : '';
  return `${path}${suffix}${hash ? `#${hash}` : ''}`;
}

/** Replaces every registered raw ID, on word boundaries so IDs never merge. */
export function replaceIdsIn(value: string, registry: Registry): string {
  let next = value;
  for (const [raw, synthetic] of registry.ids) {
    next = next.replace(new RegExp(`(?<![0-9])${escapeRegex(raw)}(?![0-9])`, 'g'), synthetic);
  }
  return next;
}

/** Applies string replacements longest-first, then scrubs anything secret-shaped. */
export function replaceAll(value: string, registry: Registry): string {
  let next = value;

  /*
   * Longest first, so "Example Government: 1(A)" wins over "Example Government".
   *
   * Each string is matched in its plain form and in its HTML-entity forms.
   * Saved Schoology pages contain double-encoded attribute values such as
   * `aria-label="Physics &amp;amp; Engineering"`, which arrive here
   * still carrying one layer of encoding after parsing.
   */
  const entries = Array.from(registry.strings.entries()).sort((a, b) => b[0].length - a[0].length);
  for (const [raw, replacement] of entries) {
    for (const variant of entityVariants(raw)) {
      if (!next.includes(variant)) continue;
      next = next.split(variant).join(replacement);
    }
  }

  next = replaceIdsIn(next, registry);

  for (const pattern of SECRET_PATTERNS) {
    pattern.lastIndex = 0;
    next = next.replace(pattern, (match) =>
      // Keep already-synthetic values and ordinary words intact.
      /^[0-9]+$/.test(match) ? match : 'REDACTED',
    );
  }

  return next;
}

/** A string as it can appear after zero, one or two rounds of HTML encoding. */
export function entityVariants(value: string): string[] {
  const once = value.replace(/&/g, '&amp;');
  const twice = once.replace(/&/g, '&amp;');
  return Array.from(new Set([value, once, twice]));
}

function escapeRegex(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
